### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by phoe** [Krzysztof-Piekarski/Tank_2D_Game_21.08.2022#1]
https://github.com/Krzysztof-Piekarski/Tank_2D_Game_21.08.2022/blob/84a771f8c9e26d522fe0eae6ebd12f38e19ce1b0/Shooting.cpp#L8-L33

--------

In L14 we create a new object and immediately add a pointer to it to a container:

https://github.com/Krzysztof-Piekarski/Tank_2D_Game_21.08.2022/blob/84a771f8c9e26d522fe0eae6ebd12f38e19ce1b0/Shooting.cpp#L14

Then, in L29 we remove the pointer from the container but we do not delete the object:

https://github.com/Krzysztof-Piekarski/Tank_2D_Game_21.08.2022/blob/84a771f8c9e26d522fe0eae6ebd12f38e19ce1b0/Shooting.cpp#L29

The solution is to modify the function to delete the object while removing the pointer:

```diff
 		if (shots[i]->shape.getPosition().x < 0 + window.getView().getCenter().x - window.getSize().x / 2 ||
 			shots[i]->shape.getPosition().x > window.getView().getCenter().x + window.getSize().x / 2 ||
 			shots[i]->shape.getPosition().y < 0 + window.getView().getCenter().y - window.getSize().y / 2 ||
 			shots[i]->shape.getPosition().y > window.getView().getCenter().y + window.getSize().y / 2)
 		{
+			delete shots[i];
 			shots.erase(shots.begin() + i);
 		}
 	}
```

**Comment by Krzysztof-Piekarski** [comment]
Thank you very much.
Issue has been solved.
